version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /hello.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: DeploymentScripts/install_dependencies
      timeout: 300
      runas: root
    - location: DeploymentScripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: DeploymentScripts/stop_server
      timeout: 300
      runas: root

